---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
  namespace: webpage
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: webpage-service
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webpage
  namespace: webpage
  labels:
    app: webpage-service
spec:
  selector:
    matchLabels:
      app: webpage-service
  template:
    metadata:
      labels:
        app: webpage-service
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      containers:
        - name: server
          image: registry.gitlab.com/kamackay/webpage:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              memory: 10M
          volumeMounts:
            - mountPath: /log
              name: varlog
      volumes:
        - name: varlog
          emptyDir: {}
